### ISSUE TITLE
v0.8 issue

### ISSUE THREAD

**Issue by enrique89** [robvanoostenrijk/BrcmPatchRAM#5]
Hi @robvanoostenrijk, Thanks for the latest release. 

I just downloaded it and installed the release build (not the debug) via Kext Drop, like I did with v.06a. I then restarted my computer and logged back in. I've lost Bluetooth connectivity with my Apple keyboard, yet the Apple Magic Trackpad still connects and works normally.

I've tried manually turning off and on the keyboard, and I've tried pairing it via the Bluetooth system preferences pane and the Keyboard system preferences pane. Here's a screenshot of the "cat /var/log/system.log | grep -i brcm[fp]" Terminal command you gave to check the status. And a screenshot of my Bluetooth System Profiler.

Any guesses you may have would be appreciated!

![diagnostic](https://cloud.githubusercontent.com/assets/10439420/5692636/b466bd32-98cb-11e4-986e-e52157645170.png)

![2015-01-10 01 23 05 pm](https://cloud.githubusercontent.com/assets/10439420/5692640/e8d68f66-98cb-11e4-8808-d4c5667a467f.png)

**Comment by robvanoostenrijk** [comment]
@enrique89,

It looks like:
* You installed the debug version (or I mixed up the release package)
* You did not fully shutdown your Mac after installing the new version.
  Because of that the previous firmware is still loaded in the device. In order to flush the firmware from your bluetooth you need to fully shutdown your machine.

Try doing that and see the result?

**Comment by enrique89** [comment]
@robvanoostenrijk,

Thanks for the suggestions. I installed v.1.0.8 based on your post this morning, and fully shut down my Mac after installing it. No luck. Then I tried installing the debug version, no luck either. Here's the log. It's so strange to me that it's pairing to the trackpad but not the keyboard.


![2015-01-12 12 10 18 pm](https://cloud.githubusercontent.com/assets/10439420/5707117/240b6cbc-9a54-11e4-8773-3787ba77a239.png)

**Comment by robvanoostenrijk** [comment]
@enrique89,

Your log file is missing the last few lines, can you provide those?

Also is the firmware version showing in Bluetooth profiler correct?

**Comment by enrique89** [comment]
@robvanoostenrijk,

Here you go. I went back and installed the non-debug version, shut down, and then upon restart re-ran the cat /var/log/system.log | grep -i brcm[fp] command in Terminal. So here is the output.

And yes, the firmware version is correct (screenshot attached).

![2015-01-12 12 24 20 pm](https://cloud.githubusercontent.com/assets/10439420/5707338/0f7ac836-9a56-11e4-89a3-2438ce924ec6.png)
![2015-01-12 12 23 14 pm](https://cloud.githubusercontent.com/assets/10439420/5707339/0f7b7330-9a56-11e4-8a99-870d2c490201.png)

**Comment by robvanoostenrijk** [comment]
@enrique89,

BrcmPatchRAM is correctly upgrading the firmware. There is nothing else it does, neither has the firmware for your device changed recently.

It's clearly between your device and OS X only. 

Did you try and put new batteries into the device? I've had issues with an Apple keyboard and bad batteries.

Additionally try turning off WiFi and other sources of interference, iPhone, iPad etc. Also any devices you might have ever paired the device with.

**Comment by enrique89** [comment]
@robvanoostenrijk, 

Thank you for your troubleshooting. Whenever it ends up being something so simple, I just want to smack myself. My iPad had previously paired with the keyboard and was paired with it, which was clearly preventing my computer from pairing with it again. 

Closing.

**Comment by robvanoostenrijk** [comment]
@enrique89,

Great that you were able to resolve the issue and thank you for reporting back.
